trigger:
- main

pool:
  name: Telecom_pool

steps:

- script: |
    cd /d "$(Build.SourcesDirectory)\environments\preprod"
    terraform init
  displayName: "Terraform Init"

- script: |
    cd /d "$(Build.SourcesDirectory)\environments\preprod"
    terraform validate
  displayName: "Terraform Validate"

- script: |
    cd /d "$(Build.SourcesDirectory)\environments\preprod"
    terraform plan
  displayName: "Terraform Plan"

- script: |
    cd /d "$(Build.SourcesDirectory)\environments\preprod"
    terraform apply -auto-approve
  displayName: "Terraform Apply"
