trigger:
- main

pool:
  name: Telecom-pool

steps:

- script: |
    cd environments/preprod
    terraform init
  displayName: "Terraform Init"

- script: |
    cd environments/preprod
    terraform validate
  displayName: "Terraform Validate"

- script: |
    cd environments/preprod
    terraform plan
  displayName: "Terraform Plan"

- script: |
    cd environments/preprod
    terraform apply -auto-approve
  displayName: "Terraform Apply"
